
trigger:
  branches:
    include:
      - refs/tags/*

stages:
- stage: Stage1
  jobs:
  - job: ShowVariables
    displayName: Show variables
    steps:
    - task: CmdLine@2
      displayName: Show variables
      inputs:
        script: 'printenv'

